# Generated by Django 5.0 on 2024-01-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=150)),
                ('contact_no', models.CharField(max_length=150)),
                ('prfile_img', models.ImageField(upload_to='app/profile_imgs')),
            ],
        ),
    ]
